### PR TITLE
Merge upstream (chrusty/protoc-gen-jsonschema)

### PR DESCRIPTION
**Pull request by ceason**
This PR merges chrusty's upstream changes into the RedVentures fork.

### CODE REVIEW

**Comment by huttotw** [comment]
@clocklear @thestephenstanton Chris wants to merge upstream updates from Chrusty into our fork. This will change the way maps are generated, what do you think?

**Comment by ceason** [comment]
Hmm interesting. What does it change? Like how does it look before vs after?

**Comment by thestephenstanton** [comment]
Yeah I would like to know what exactly it is changing

**Comment by thestephenstanton** [comment]
I would argue that since we are not using protobuf anymore, and the version we have works the way we want, there should be no reason to merge in anything new. 

But I assume that there is a reason for this merge @ceason ? From their commit messages, it really doesn't seem like they are adding in anything substantial. Just some cleanup

**Comment by thestephenstanton** [comment]
So looking through the commits, it looks like he really just added support for maps of some key to value type of message. Which, correct me if I'm wrong, I am pretty sure we don't use at all?

**Comment by clocklear** [comment]
I think this will change the schemas of our existing protobuf messages that use the map type.  It would be nice if we could test out this change with a couple messages to ensure our validator can speak these types.

To be fair, the way maps are generated currently doesn't work anyway, but still.

**Comment by clocklear** [comment]
This really effects @thestephenstanton and the data lake.  If he's good with it, I'm good with it.

**Comment by thestephenstanton** [comment]
@clocklear This actually won't affect the data lake at all since I switched to just using the proto descriptor sets for legacy stuff. I think the only touch point will be on tagular since it is verifying the messages

**Review by clocklear — APPROVED** [review]

**Comment by ceason** [comment]
Now that @clocklear has approved, how do we get this merged?

**Review by thestephenstanton — CHANGES_REQUESTED** [review]
So we can't change this because of the way we want maps to be generated. A bit complicated to explain over text, but can explain on the whiteboard nearby if you are interested.

If you want to do a PR to include just the description stuff, then that'd be fine to merge in.

**Pull request closed without merging**
